# -*- coding: utf-8 -*-
"""Morphology.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JuHjRwYXFo4W1OpFUDixeYBhhoGeaz-x
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread('j.jpg',0)
kernel = np.ones((5,5),np.uint8)

erosion = cv2.erode(img,kernel,iterations = 1)
cv2_imshow(erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

dilation = cv2.dilate(img,kernel,iterations = 1)
cv2_imshow(dilation)
cv2.waitKey(0)
cv2.destroyAllWindows()

opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
cv2_imshow(opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)
cv2_imshow(closing)
cv2.waitKey(0)
cv2.destroyAllWindows()